image: docker:latest

services:
  - docker:dind

build_docker:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:latest" --file Dockerfile.gitlab .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  tags:
    - docker
